//go:generate go run .
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	// 產生檔案的目標路徑
	output := "../../../handler" + "/gen_check.go"

	// 確保目錄存在
	if err := os.MkdirAll(filepath.Dir(output), os.ModePerm); err != nil {
		panic(err)
	}

	f, err := os.Create(output)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	content := `package handler

// Code generated by gen-checks; DO NOT EDIT.
// Be sure to explicitly check the interfaces you will use at compile time

var (
    _ IPlatformHandler = (*BinanceHandler)(nil)
	_ IPlatformHandler = (*OKXHandler)(nil)
)
`
	if _, err := f.WriteString(content); err != nil {
		panic(err)
	}

	fmt.Println("Service Interface Check Generated OK", output)
}
